from math import pi
from numpy import deg2rad

# GRAPH GENERATION PARAMETERS
MAX_SEGMENT_INCLINATION = 10/180 * pi  # rad
MIN_ANGLE_FOR_INTERSECTIONS = deg2rad(50)
SPLINE_PLOT_PRECISSION = 0.3

# MESH GENERATION PARAMETERS
MIN_DIST_OF_MESH_POINTS = 0.1  # meters
N_ANGLES_PER_CIRCLE = 10
TUNNEL_AVG_RADIUS = 3 # meters