from math import pi
from numpy import deg2rad
PROB_DIVERGENCE = 0.1
PROB_STOP = 0.1
MAX_SEGMENT_INCLINATION = 10/180 * pi  # rad
MIN_DIST_OF_MESH_POINTS = 0.1  # meters
TUNNEL_AVG_RADIUS = 3
MIN_ANGLE_FOR_INTERSECTIONS = deg2rad(50)
N_ANGLES_PER_CIRCLE = 10
SPLINE_PLOT_PRECISSION = 0.3
TUNNEL_AVG_RADIUS = 3